### ISSUE TITLE
Cannot make this work for Linux Mint 19

### ISSUE THREAD

**Issue by evboliveira** [bigbigmdm/GAOMON-S620-in-LINUX#5]
Hello,
I have used my Gaomon S620 tablet, with the Linux Mint 20+ versions for quite a long time, and your instructions have always worked right out of the box. However, I had to downgrade to Linux Mint 19 because I am using an older machine (an iMac12), and now, I can't configure the key buttons on the tablet. 

My output for `xsetwacom --list` after changing the **/usr/share/X11/xorg.conf.d/70-wacom.conf** file is

> GAOMON Gaomon Tablet stylus     	id: 10	type: STYLUS    
GAOMON Gaomon Tablet eraser     	id: 16	type: ERASER 

My current Linux kernel is 4.15.

Is there a way of fixing this?

Thank you very much!

**Comment by bigbigmdm** [comment]
Hello! I tested this script in Linux Mint 20.3 and Linux Mint 19.3 (kernel 5.4.0-122-generic) - everything is fine!In Linux Mint 18 Sarah (kernel 4.4.0-21-generic) I had the following problems:The xsetwacom --list command reports: GAOMON Gaomon Tablet stylus id: 11 type: STYLUS    GAOMON Gaomon Tablet eraser id: 14 type: ERASER    GAOMON Gaomon Tablet pad id: 15 type: PAD The script writes errors:Wrong offset in the Wacom Button Actions property.Incorrect offset in the Wacom Button Actions property.Incorrect offset in Wacom Button Actions property.Pad buttons do not play but pad stylus plays correctly. On the Russian page (http://sourceforge.net/projects/linuxwacom/files/latest/download) I found the instructions for replacing the wacom drivers:sudo apt-get install pkg-config make xutils-dev libtool xserver-xorg-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libudev-devOpen in a browser http://sourceforge.net/projects/linuxwacom/files/latest/download and save it.Unpack the archivecd /...<your download folder>.../xf86-input-wacom-0.36.0/./configure --prefix=/usrmakeand copy the drivers to /lib/modules/. This script doesn't compile in LM18... That's all for today... Regards, Michail     11.10.2022, 18:21, "Estevao VBO" ***@***.***>:
Hello,
I have used my Gaomon S620 tablet, with the Linux Mint 20+ versions for quite a long time, and your instructions have always worked right out of the box. However, I had to downgrade to Linux Mint 19 because I am using an older machine (an iMac12), and now, I can't configure the key buttons on the tablet.
My output for xsetwacom --list after changing the /usr/share/X11/xorg.conf.d/70-wacom.conf file is

GAOMON Gaomon Tablet stylus     	id: 10	type: STYLUS
GAOMON Gaomon Tablet eraser     	id: 16	type: ERASER

My current Linux kernel is 4.15.
Is there a way of fixing this?
Thank you very much!

**Comment by bigbigmdm** [comment]
Hello! Can you test an update of the wacom driver from the archive ( https://github.com/linuxwacom/xf86-input-wacom/wiki/Building-The-Driver ) or build a new driver from the source code ( https://github.com/linuxwacom/input-wacom/wiki/Installing-input-wacom-from-source ) ?  Regards, Michail11.10.2022, 18:21, "Estevao VBO" ***@***.***>:
Hello,
I have used my Gaomon S620 tablet, with the Linux Mint 20+ versions for quite a long time, and your instructions have always worked right out of the box. However, I had to downgrade to Linux Mint 19 because I am using an older machine (an iMac12), and now, I can't configure the key buttons on the tablet.
My output for xsetwacom --list after changing the /usr/share/X11/xorg.conf.d/70-wacom.conf file is

GAOMON Gaomon Tablet stylus     	id: 10	type: STYLUS
GAOMON Gaomon Tablet eraser     	id: 16	type: ERASER

My current Linux kernel is 4.15.
Is there a way of fixing this?
Thank you very much!

**Comment by bigbigmdm** [comment]
The problem is not solvable
